### ISSUE TITLE
Subscribe to a stream of events using tailable cursors

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/Akka.Persistence.MongoDB#11]
This is a free idea and needs some investigation - as MongoDB supports [capped collections](https://docs.mongodb.org/manual/core/capped-collections/) and [tailable cursors](https://docs.mongodb.org/manual/reference/glossary/#term-tailable-cursor), could we utilize those features inside the journal to create pub/sub streams inside journal, to which other actors could subscribe to?

**Comment by Silv3rcircl3** [comment]
I have created a little gist, is this what you have in mind? 
https://gist.github.com/Silv3rcircl3/1cddcd3314073dcd760c

![image](https://cloud.githubusercontent.com/assets/6583600/11029275/3b45290e-86c6-11e5-86bc-c126faad774d.png)
