### ISSUE TITLE
Index PersistenceId

### ISSUE THREAD

**Issue by me-slove** [akkadotnet/Akka.Persistence.MongoDB#129]
Since PersistenceId is used all the time and MongoDB likes to be able to use an index.  Can this be created at the time the collections are built?

It's easy enough to build it after the fact but it is also easy to forget and it kills performance.

**Comment by Aaronontheweb** [comment]
@me-slove I thought we already had one - do we not? If so then yes, we should definitely add one.

**Comment by me-slove** [comment]
I did look in the code and did not see it (or experience it when using the persister), but I may have missed something in the configuration.

**Comment by Aaronontheweb** [comment]
Test this out on https://github.com/petabridge/akkadotnet-cluster-workshop/blob/dev/docker-compose.yaml

**Comment by Aaronontheweb** [comment]
Wow, turns out we were not indexing by default due to a bad configuration default. This has been resolved as part of Akka.Persistence.MongoDb v1.4.21 https://github.com/akkadotnet/Akka.Persistence.MongoDB/releases/tag/1.4.21
