### ISSUE TITLE
Use MongoDb transactions for AtomicWrites

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Persistence.MongoDB#190]
> Ah, let me rephrase that - the `InsertMany` call will only _send_ multiple events at once if they all come from the same `PersistAll` or `PersistAllAsync` command from one `PersistentActor`. Otherwise, all of the `InsertMany` calls will only contain a single message in it.

Yes.

Let's say you do a persist all with 2 events.

If you do not use a transaction and an error occurs on the second document when doing an insert many, you should get a persistence failure but the first event will be stored.

_Originally posted by @simonlaroche in https://github.com/akkadotnet/Akka.Persistence.MongoDB/issues/186#issuecomment-801976416_

---

We probably need to insert the following `MongoDbJournal` call inside a Mongo transaction:

https://github.com/akkadotnet/Akka.Persistence.MongoDB/blob/53326fc2739728f93bf8e0c85983fb1880f39988/src/Akka.Persistence.MongoDb/Journal/MongoDbJournal.cs#L246

Since `InsertManyAsync` doesn't make any atomicity guarantees.

The downside, if we do this, is that Akka.Persistence.MongoDb will no longer be supported on stand-alone MongoDb - everything will have to be run inside at least a single node Mongo ReplicaSet, since transactions are not supported in stand-alone. Does that seem like an acceptable change to make to the driver? Just asking since we're not big production users of MongoDb ourselves.

**Comment by simonlaroche** [comment]
Mayby on opt-in setting?

**Comment by Aaronontheweb** [comment]
We could give that a try - everyone running this plugin in production _should_ be using a ReplicaSet, but local development and testing is probably still often done via stand-alone.

**Comment by jaydeboer** [comment]
@Aaronontheweb You can run Mongo as a single node replica set and if you want to use Mongo2Go for testing that also supports single node replica sets.  In a project at work (non-akka) we are using change streams in Mongo which mandates replica sets and we are having no issues running on our dev boxes without a proper cluster.  So that may not be much of an ask of the developers.

**Comment by Aaronontheweb** [comment]
Closed via https://github.com/akkadotnet/Akka.Persistence.MongoDB/pull/301
