### ISSUE TITLE
Queries randomly skip an event every great once in a while.

### ISSUE THREAD

**Issue by jaydeboer** [akkadotnet/Akka.Persistence.MongoDB#296]
**Version Information**
```
<PackageReference Include="Akka.DependencyInjection" Version="1.4.49" />
<PackageReference Include="Akka.Hosting" Version="1.0.3" />
<PackageReference Include="Akka.Persistence.MongoDB" Version="1.4.48" />
```

**Describe the bug**
When there are a fair number of writes and reads happening at the same time, an event will be skipped.  I have tested this against MongoDB running as a single node cluster running in Docker.  I have reproduced the same behavior with `EventsByTag` and `AllEvents` queries.  It may take many thousands of events for one to be skipped.  

**To Reproduce**
I have a sink setup as follows:

```
long _lastProcessedId;
protected override void OnReplaySuccess()
{
    var materializer = Context.Materializer();
    var self = Self;

    _query.EventsByTag(_portString, Offset.Sequence(_lastProcessedId))
        .Where(e => e.Event is DataPacketReceivedEvent)
        .RunWith(Sink.ActorRef<EventEnvelope>(self, UnexpectedEndOfStream.Instance), materializer);
    base.OnReplaySuccess();
}
```

**Expected behavior**
Each event matching the query would be processed.

**Actual behavior**
One in a great while, one offset will be missing.

**Environment**
.NET 7
Windows 11 and MacOS both exhibit the same behavior.

**Additional context**
If I add artificial delays to the process, I get to the point where I cannot reproduce the issue, or it happens so infrequently that it looks like it never happens.

This is a screenshot of the events, the middle one being skipped on one of my runs. The ordering seems fine and these are the only persists that would have matched the query that was running at that time.

![image](https://user-images.githubusercontent.com/5098996/220186023-d1513dcf-27bf-460c-b1c8-817f18bbe506.png)

**Comment by Aaronontheweb** [comment]
Thanks! We'll take a look at this

**Comment by jaydeboer** [comment]
I ran this against a proper cluster and I had 3 missed events in 110,000 over a 5 minute span. Another piece I forgot to mention earlier is that if I delete all of the events and snapshots for the actor that is consuming the journal, then the skipped offsets are no longer skipped.  It sure seems like it has to be in the timing of the actual persists in Mongo.

**Comment by Aaronontheweb** [comment]
I think this should be fixed via https://github.com/akkadotnet/Akka.Persistence.MongoDB/pull/301 - this will be released in Akka.Persistence.MongoDb v1.5.1.
