### ISSUE TITLE
Convert MongoDb test suite to use a single-node MongoDb replica set

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Persistence.MongoDB#298]
> @Aaronontheweb You can run Mongo as a single node replica set and if you want to use Mongo2Go for testing that also supports single node replica sets.  In a project at work (non-akka) we are using change streams in Mongo which mandates replica sets and we are having no issues running on our dev boxes without a proper cluster.  So that may not be much of an ask of the developers.

_Originally posted by @jaydeboer in https://github.com/akkadotnet/Akka.Persistence.MongoDB/issues/190#issuecomment-1437797801_

**Comment by Aaronontheweb** [comment]
Need to figure out how to update our test suite to run Mongo2Go as a single node replica set, so we can support adding transactions  in https://github.com/akkadotnet/Akka.Persistence.MongoDB/issues/190 in order to try to solve https://github.com/akkadotnet/Akka.Persistence.MongoDB/issues/296

**Comment by jaydeboer** [comment]
Here is where I found that info https://github.com/Mongo2Go/Mongo2Go#single-server-replica-set-mode-to-enable-transactions

Hope that helps!

**Comment by eaba** [comment]
@Aaronontheweb I am working on it.

![image](https://user-images.githubusercontent.com/8049896/220886400-77867a4a-292e-4781-aaca-e4e8bc6d43ec.png)

**Comment by Aaronontheweb** [comment]
@eaba can you open a draft PR?

**Comment by eaba** [comment]
https://github.com/akkadotnet/Akka.Persistence.MongoDB/pull/300
