### ISSUE TITLE
Support for `[BsonDiscriminator]` attribute

### ISSUE THREAD

**Issue by ncthbrt** [akkadotnet/Akka.Persistence.MongoDB#51]
When I write an entry to the journal, it currently includes a `_t` field in the `Payload` object, which contains the full assembly qualified type name. I added the attribute `[BsonDiscriminator("customName")]` in an effort to ensure that my persistence models are hardened against accidental namespace changes, and to better support message versioning, however this attribute appears to be ignored by the serializer.

**Comment by Aaronontheweb** [comment]
@ncthbrt is this still an issue?

**Comment by ncthbrt** [comment]
We actually created a private fork of the mongo provider because of this
issue.

**Comment by Aaronontheweb** [comment]
@ncthbrt ah, the best way to handle this going forward is with the binary serialization, per https://github.com/akkadotnet/Akka.Persistence.MongoDB/issues/72
