### ISSUE TITLE
Actor won't recover from EventJournal

### ISSUE THREAD

**Issue by lesscodetxm** [akkadotnet/Akka.Persistence.MongoDB#60]
I started my actor system today and got:

`2019-06-06 08:51:51.697 -05:00 [ERR] Persistence failure when replaying events for persistenceId [nuxeo-document-release]. Last known sequence number [0]
Akka.Persistence.RecoveryTimedOutException: Recovery timed out, didn't get event within 30s, highest sequence number seen 0.`

I had restarted the system several times yesterday and saw my actors successfully recover from the same repository. I can access the EventJournal directly and can see the events. The connection string in hocon is correct.

Intellitrace in Visual Studio shows this:

` Exception caught: MongoDB.Bson.BsonSerializationException ... "There is already a discriminator convention registered for type ..."`

I see many such errors in the trace (hundreds)?

**Comment by Horusiath** [comment]
It looks like your MongoDB driver cannot deserialize underlying type. Make sure, that you've registered your type as mentioned in [README](https://github.com/AkkaNetContrib/Akka.Persistence.MongoDB#serialization).

**Comment by lesscodedotnet** [comment]
The readme says: `Since now, all types are registered automatically for you so you don't need to use BsonClassMap to serialize/deserialize your types!`

What am I missing. I had assumed I didn't need to register anything manually.

**Comment by Aaronontheweb** [comment]
@lesscodedotnet not sure - I'm not a Mongo expert, but this seems like an issue with the driver itself.

If we need to make some changes to our README or some changes to how we call the driver, I would welcome some suggestions. In the meantime, going to mark this issue as closed.
