### ISSUE TITLE
Event type difference between EventsByTag and EventsByPersistenceId

### ISSUE THREAD

**Issue by acesyde** [akkadotnet/Akka.Persistence.MongoDB#61]
Hi,

I want to retrieve events by tags and by persistent ids

With _EventsByPersistenceId_ when i call
`mongoDbReadJournal.EventsByPersistenceId(identity.Value, 0L, long.MaxValue)`

_EventEnvelope.Event_ type is "CommittedEvent"

With _EventsByTag_ when i call
`mongoDbReadJournal.EventsByTag(aggregateName, Offset.NoOffset())`

_EventEnvelope.Event_ type is "byte[]"

I don't understand why EventsByTag not return a "CommittedEvent"

Any idea about this ?

Thanks

**Comment by Aaronontheweb** [comment]
@acesyde sounds like a bug in the driver implementation itself - should be `CommittedEvent` for both.

**Comment by Aaronontheweb** [comment]
@acesyde I think I've figured this one out... The mechanisms that journal uses to deserialize these events are different. I'll write a test for it.

**Comment by Aaronontheweb** [comment]
Yep, this is a serialization error. Been able to verify it on #79 and I know how to fix it.
