### ISSUE TITLE
Modernize MongoDb driver calls to eliminate `OBSOLETE` warnings

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Persistence.MongoDB#81]
I'm not familiar enough with the MongoDb driver to know how to do this, even after looking at their documentation. 

But we need to replace both of these calls:

https://github.com/akkadotnet/Akka.Persistence.MongoDB/blob/3394798f189483e6ad1e215d7abdb88b79526976/src/Akka.Persistence.MongoDb/Journal/MongoDbJournal.cs#L104-L112

This call

https://github.com/akkadotnet/Akka.Persistence.MongoDB/blob/3394798f189483e6ad1e215d7abdb88b79526976/src/Akka.Persistence.MongoDb/Journal/MongoDbJournal.cs#L124-L127

And this call

https://github.com/akkadotnet/Akka.Persistence.MongoDB/blob/3394798f189483e6ad1e215d7abdb88b79526976/src/Akka.Persistence.MongoDb/Snapshot/MongoDbSnapshotStore.cs#L81-L85

With the new syntax required by the MongoDb driver. Pull requests welcome.

**Comment by SeanKilleen** [comment]
I'll take a crack at this.

**Comment by Aaronontheweb** [comment]
@SeanKilleen much appreciated! I'm working on filing some other bugs / issues I'm tackling on the Akka side of things with this driver.

**Comment by SeanKilleen** [comment]
I think it ends up being something like:

```csharp
var model = new CreateIndexModel<SnapshotEntry>(
	Builders<SnapshotEntry>
		.IndexKeys.Ascending(entry => entry.PersistenceId)
		.Descending(entry => entry.SequenceNr));

collection.Indexes.CreateOneAsync(model, cancellationToken: CancellationToken.None).Wait();
```

But I'll double-check that and ensure all the tests pass etc.

**Comment by Aaronontheweb** [comment]
The CI on this repository is fully current with the best practices we're using elsewhere in the Akka.NET project, FYI - most of the failing PRs are due to a fundamental serialization problem we're going to have to address in v1.4.0.
