### ISSUE TITLE
Akka.Persistence.MongoDB does not work with .NET Core 3

### ISSUE THREAD

**Issue by jackowild** [akkadotnet/Akka.Persistence.MongoDB#90]
Unfortunately the version of the MongoDB plugin used in this project does not work with .NET Core 3.

When running a project targeting .NET Core 3, there are BsonClassMap initializer exceptions as described here https://jira.mongodb.org/browse/CSHARP-2595.

A fix went into v2.8.1 of the MongoDB plugin but they dropped support for .NET 4.5 which this project currently supports.

Should we drop support for 4.5 and increase to 4.5.2 like the MongoDB plugin? @Aaronontheweb this is probably a question for you.

PS a workaround is to add a nuget reference to the latest MongoDB plugin in your project.

**Comment by Aaronontheweb** [comment]
@jackowild hmmmm.... I'll see about getting this thing bumped to run off of the latest v1.4.0-beta builds, including .NET Standard 2.0 targeting moving forward.

**Comment by Aaronontheweb** [comment]
Actually, a better fix is just moving onto .NET 4.5.2 for this project for the time being.

**Comment by Aaronontheweb** [comment]
Resolved via https://github.com/akkadotnet/Akka.Persistence.MongoDB/pull/67
